# Generated by Django 4.2 on 2023-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=555, verbose_name='Descripcion de Producto')),
                ('stok', models.PositiveIntegerField(verbose_name='Stock de Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio Producto')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
