# Generated by Django 4.2 on 2023-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=254, verbose_name='Apellidos')),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razon Soacial')),
                ('direccion', models.CharField(max_length=555, verbose_name='Direccion')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usurios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='stok',
            new_name='stock',
        ),
    ]
